[project]
name = "IXV-util-MarkItDown"
version = "0.1.0"
description = "Simple docx to Markdown converter"
authors = [
    {name = "IXV Team", email = ""},
]
license = {text = "MIT"}
requires-python = ">=3.8"
readme = "README.md"
dependencies = []

[project.scripts]
markitdown = "markitdown.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["markitdown"]

[tool.uv]
dev-dependencies = [
    "pyinstaller>=6.0.0",
    "py2app>=0.28.0",
    "pytest>=7.0.0",
    "black>=23.0.0",
    "ruff>=0.1.0",
]