name: Copy README to docs/

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 手動実行も可能にする

jobs:
  copy-readme:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: 📄 README.md を docs/ に複製
        run: |
          mkdir -p docs
          cp README.md docs/README.md

      - name: 📤 docs/README.md をコミット＆プッシュ
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # ファイルが変更された場合のみコミット
          if ! git diff --quiet docs/README.md; then
            git add docs/README.md
            git commit -m "🔄 Auto-update docs/README.md from root README.md"
            git push
          else
            echo "✅ docs/README.md に変更はありません"
          fi
