name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
            arch: x86
            binary_name: IXV-util-MarkItDown.exe
            asset_name: IXV-util-MarkItDown-windows-x86.exe
          - os: macos-13
            platform: macos
            arch: x86
            binary_name: IXV-util-MarkItDown
            asset_name: IXV-util-MarkItDown-macos-x86
          - os: macos-latest
            platform: macos
            arch: arm64
            binary_name: IXV-util-MarkItDown
            asset_name: IXV-util-MarkItDown-macos-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: |
          uv sync

      - name: Build binary with PyInstaller
        run: |
          uv run python scripts/build.py
        shell: bash

      - name: List dist directory contents
        shell: bash
        run: |
          echo "Contents of dist directory:"
          ls -la dist/ || echo "dist directory not found"

      - name: Rename binary for release
        shell: bash
        run: |
          cd dist
          if [ "${{ matrix.platform }}" = "windows" ]; then
            mv IXV-util-MarkItDown.exe ${{ matrix.asset_name }}
          else
            mv IXV-util-MarkItDown ${{ matrix.asset_name }}
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: dist/${{ matrix.asset_name }}
          retention-days: 30

  release:
    name: Create release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -la artifacts/

      - name: Extract README content
        id: readme_content
        run: |
          # Extract content from "## 使い方" to before "### 画像の取り扱い"
          awk '/^## 使い方/,/^### 画像の取り扱い/' README.md | head -n -1 > usage_content.txt
          
          # Store in GitHub output (handle multiline content)
          {
            echo 'USAGE_CONTENT<<EOF'
            cat usage_content.txt
            echo 'EOF'
          } >> $GITHUB_OUTPUT

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: リリース ${{ github.ref_name }}
          body: |
            ## 変更内容

            詳細な変更リストについては[コミット履歴](https://github.com/${{ github.repository }}/commits/${{ github.ref_name }})をご覧ください。

            ## ダウンロード

            - **Windows (x86)**: `IXV-util-MarkItDown-windows-x86.exe`
            - **macOS (x86)**: `IXV-util-MarkItDown-macos-x86`
            - **macOS (ARM64)**: `IXV-util-MarkItDown-macos-arm64`

            ${{ steps.readme_content.outputs.USAGE_CONTENT }}

            ## システム要件

            - **Windows**: Windows 10 以降 (x86/x64)
            - **macOS**: macOS 10.15 (Catalina) 以降 (Intel/Apple Silicon)

            実行可能ファイルは外部依存なしで動作します。
          draft: false
          prerelease: false

      - name: Upload Windows binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/IXV-util-MarkItDown-windows-x86.exe/IXV-util-MarkItDown-windows-x86.exe
          asset_name: IXV-util-MarkItDown-windows-x86.exe
          asset_content_type: application/octet-stream

      - name: Upload macOS x86 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/IXV-util-MarkItDown-macos-x86/IXV-util-MarkItDown-macos-x86
          asset_name: IXV-util-MarkItDown-macos-x86
          asset_content_type: application/octet-stream

      - name: Upload macOS ARM64 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/IXV-util-MarkItDown-macos-arm64/IXV-util-MarkItDown-macos-arm64
          asset_name: IXV-util-MarkItDown-macos-arm64
          asset_content_type: application/octet-stream