name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            extension: ""
          - os: macos-latest
            platform: macos
            extension: ""
          - os: windows-latest
            platform: windows
            extension: ".exe"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pytest
          pip install .

      - name: Run tests
        run: pytest

      - name: Build executable
        run: |
          pyinstaller --onefile --distpath dist/${{ matrix.platform }} --name MarkItDown wrapper.py

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/${{ matrix.platform }}/MarkItDown${{ matrix.extension }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
